# Generated by Django 6.0.6 on 2026-07-26 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_category_details_course_description_courseoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, default='fa-solid fa-layer-group', help_text='Font Awesome class, for example: fa-solid fa-code', max_length=80),
        ),
        migrations.AlterField(
            model_name='courseoption',
            name='name',
            field=models.CharField(help_text='Example: Weekend Batch, Certificate or Mentorship', max_length=120),
        ),
        migrations.AlterField(
            model_name='courseoption',
            name='price_delta',
            field=models.IntegerField(default=0, help_text='Extra amount added to course price. Use 0 for a free option.'),
        ),
    ]
