# Generated by Django 6.0.5 on 2026-08-31 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_category_icon_alter_courseoption_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, default='fa-solid fa-layer-group', help_text='icon ka naam dalo jaise: fa-solid fa-code', max_length=80),
        ),
        migrations.AlterField(
            model_name='courseoption',
            name='name',
            field=models.CharField(help_text='Ex: Weekend Batch ya Certificate', max_length=120),
        ),
        migrations.AlterField(
            model_name='courseoption',
            name='price_delta',
            field=models.IntegerField(default=0, help_text='extra paise jo add honge, free hai to 0 rakho'),
        ),
    ]
